baseurl                         = "/"
title                           = "Governance"
defaultContentLanguage          = "id"
defaultContentLanguageInSubdir  = false
enableRobotsTXT                 = true
#disableKinds                   = ["RSS", "taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject      = "true"
disqusShortname                 = ""
#googleAnalytics                 = ""
#adsensePublisher                = ""
#pluralizeListTitles             = false
#disableLanguages                = []

[markup.goldmark.renderer]
  unsafe                        = false

[outputs]
  home                          = [ "html", "humans" ]

  [outputFormats.humans]
    baseName                    = "humans"
    isPlainText                 = true
    mediaType                   = "text/plain"

[permalinks]
  post                          = "/:year/:month/:title/"

[params]
  description                   = "Collaborate with government agencies on codes, data, information, policies, and open government efforts."
  socialShare                   = ["whatsapp", "facebook", "twitter", "email"]
  socialProfiles                = ["https://github.com/iap/gov"]

[params.readingtime]
  enable                        = true

#[service]

[Languages]
  [Languages.en]
    languageCode                = "en"
    languageName                = "English"
    contentDir                  = "content/en"
    weight                      = 1

  [Languages.id]
    languageCode                = "id"
    languageName                = "Indonesia"
    title                       = "Governance"
    description                 = "Bekerja sama dengan lembaga pemerintah dalam kode, data, informasi, kebijakan, dan upaya pemerintahan terbuka."
    contentDir                  = "content/id"
    weight                      = 2

