baseurl = "/"
title = "Governance"

enableRobotsTXT = true

languageCode = "en-us"
languageLang = "en"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = "true"

timeout = 3000

ignoreFiles = [ "^OWNERS$", "README.md", "^node_modules$" ]

[blackfriday]
hrefTargetBlank = true
fractions = false

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

# Enable Git variables like commit, lastmod
enableGitInfo = false

# Be explicit about the output formats. We (currently) only want an RSS feed for the home page.
[outputs]
home = [ "HTML" ]
page = [ "HTML"]
section = [ "HTML"]

[outputFormats]
[outputFormats.RSS]
baseName = "feed"

[permalinks]
  post = "/:year/:month/:day/:slug/"
  page = "/:filename/"

[params]
    organizationName = "Trade"
    organizationAddress = "Dr Kusuma Atmaja, 10310 Jakarta"
    # organizationLogo = "assets/logo.png"
    
    # adsensePublisher = "ca-pub-XXXXXX"
    # googleAnalytics = "UA-XXXXXX-XX"
    # appleItunesApp = "app-id=XXXXXX, app-argument=app-name://link/to/app-content" # required if you want to add an app banner with iOS app

    socialProfiles = ["https://github.com/iap/gov"]

[taxonomies]
  tag = "tags"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
